language: ruby
sudo: false
before_install: gem install bundler
env: SUITE="rspec"
script: bundle exec $SUITE
matrix:
  fast_finish: true
  include:
  - rvm: 2.3
  - rvm: 2.4
  - rvm: 2.5
  - rvm: 2.6
  - rvm: 2.6 # Only run RuboCop on the latest Ruby
    env: SUITE="rubocop"
  - rvm: ruby-head
  allow_failures:
  - rvm: ruby-head
